#cloud-config
groups:
  - docker
users:
  - name: takuser
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  expire: false
  users:
    - name: root
      password: $y$j9T$r7irXlVE3HgZTQDoqDZ84.$e3YsPTak5E8EKVuYpfXoXH2frWAXxwVwPhgjIIOEoeA
    - name: takuser
      password: $y$j9T$r7irXlVE3HgZTQDoqDZ84.$e3YsPTak5E8EKVuYpfXoXH2frWAXxwVwPhgjIIOEoeA
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - net-tools
  - unzip
  - zip
  - jq
package_update: true
final_message: |
  OHMR cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime